#!/bin/sh

subcommand="${1}";
shift

# Try to figure out what the project root directory is
project_root=$(pwd)
while [[ ! -d "${project_root}/.db" ]]; do

  if [ "${project_root}" = "/" ]; then
    if [ "${subcommand}" == "init" ]; then
      project_root=$(pwd)
      break
    else
      echo "fatal: Not a db repository (or any of the parent directories). Please run 'db init'.";
      exit 2
    fi
  fi

  project_root=$(cd "${project_root}/.." && pwd)
done

# Get the directory where the main script (this one) is installed
installation_root=$(dirname $(python -c 'import os,sys;print(os.path.realpath(sys.argv[1]))' $0))

# Load the colors
bin="${installation_root}/bin"
source "${bin}/include/colors"

# Default server shortname is the first one in the .db folder, or "localhost" if that folder doesn't exist yet
shortname="localhost"
if [[ -d "${project_root}/.db" ]]; then
  shortname=$(ls -d ${project_root}/.db/*/ | head -n 1 | rev | cut -f 2 -d '/' | rev)
fi
if [ "$#" -ge 1 ]; then
  if [ "${subcommand}" == "init" ]; then
    shortname="${1}"
    shift
  else
    if [[ -d "${project_root}/.db/${1}/config" ]]; then
      shortname="${1}"
      shift
    fi
  fi
fi

# for synching database CONTENTS http://www.cri.ensmp.fr/~coelho/pg_comparator/pg_comparator.html
# for synching database STRUCTURE http://mmatuson.github.io/SchemaSync/ or http://search.cpan.org/dist/MySQL-Diff/bin/mysqldiff

cmd="${installation_root}/bin/db-${subcommand}"
if [[ -f ${cmd} ]]; then
  ${cmd} "${project_root}" "${shortname}" "$@"
else
  commands=$(ls -1 ${installation_root}/bin | grep "db-" | cut -d "-" -f 2 | paste -s -d "|" -)
  echo "USAGE: db (${commands})"
  exit 1
fi