#!/bin/sh

option="${1}";
shift
db_dir=$(cd "$(dirname "$0")/."; pwd);

me=$(dirname $(python -c 'import os,sys;print(os.path.realpath(sys.argv[1]))' $0))

# for synching database CONTENTS http://www.cri.ensmp.fr/~coelho/pg_comparator/pg_comparator.html
# for synching database STRUCTURE http://mmatuson.github.io/SchemaSync/

case ${option} in
	list)
		${me}/bin/db-list "${db_dir}" "$@"
		;;
	init)
		${me}/bin/db-init "${db_dir}" "$@"
		;;
	snapshot)
		${me}/bin/db-snapshot "${db_dir}" "$@"
		;;
	restore)
		${me}/bin/db-restore "${db_dir}" "$@"
		;;
	remove)
		${me}/bin/db-remove "${db_dir}" "$@"
		;;
	*)
		echo "USAGE: db (init|list|snapshot|restore|remove)"
esac
