#!/usr/bin/env sh

command="${1}"
if [ "$#" -gt 0 ]; then shift; fi
subcommand="${1}"

# Try to figure out what the project root directory is
project_root=$(pwd)
while [ ! -d "${project_root}/.db" ]; do

  if [ "${project_root}" = "/" ]; then
    if [ "${command}" = "init" ]; then
      project_root=$(pwd)
      break
    else
      echo "fatal: Not a db repository (or any of the parent directories). Please run 'db init'.";
      exit 2
    fi
  fi

  project_root=$(cd "${project_root}/.." && pwd)
done

# Get the directory where the main script (this one) is installed
installation_root=$(dirname "$(python -c 'import os,sys;print(os.path.realpath(sys.argv[1]))' $0)")

# Load the colors
bin="${installation_root}/bin"
. "${bin}/include/colors"

# Default server alias is the server that was added first. If no servers exist yet, use "localhost"
alias="localhost"
if [ -d "${project_root}/.db" ]; then
  configs=$(find "${project_root}/.db" -type d -d 1 | wc -l)
  if [ ${configs} -gt 0 ]; then
    alias=$(find "${project_root}/.db" -type d -d 1 -print0 | xargs -0 ls -1drt | head -n 1 | rev | cut -f 1 -d '/' | rev)
  else
    if [ "${command}" != "server" ] && [ "${subcommand}" != "add" ]; then
      echo "${COLOR_RED}No database servers defined!${COLOR_NC}"
      echo "Please add a server configuration by typing ${COLOR_LIGHT_BLUE}db server add${COLOR_NC}"
      exit 1
    fi
  fi
fi

# Figure out if an alias has been provided on the command line
if [ "$#" -ge 1 ]; then
  # yes, perhaps
  if [ "${command}" = "server" ]; then
    # with the 'server' command, the alias is the third argument (server add XXX)
    if [ "$#" -ge 2 ]; then
      if [ -d "${project_root}/.db/${2}/config" ] || [ "${subcommand}" = "add" ]; then
        alias="${2}"
      fi
    fi
  else
    # with other commands, the alias is the second argument (snapshot XXX)
    if [ -d "${project_root}/.db/${1}/config" ]; then
      alias="${1}"
      shift
    fi
  fi
fi

# for synching database CONTENTS http://www.cri.ensmp.fr/~coelho/pg_comparator/pg_comparator.html
# for synching database STRUCTURE http://mmatuson.github.io/SchemaSync/ or http://search.cpan.org/dist/MySQL-Diff/bin/mysqldiff

cmd="${installation_root}/bin/db-${command}"
if [ -f "${cmd}" ]; then
  ${cmd} "${project_root}" "${alias}" "$@"
else
  commands=$(ls -1 "${installation_root}/bin" | grep "db-" | cut -d "-" -f 2 | paste -s -d "|" -)
  echo "USAGE: db (${commands})"
  exit 1
fi